version: "3"

networks:
  mdp2mailservice-network:
    driver: bridge

services:
  app:
    container_name: mdp2mailservice-0.1.0
    image: mdp2/mailservice:0.1.0
    build: .
    command: bash -c "python mdp2mailservice/init_db.py && fastapi run mdp2mailservice/main.py --port 8000 --workers 4"
    env_file: ".env.dev"
    restart: unless-stopped
    ports:
      - "8111:8000"
    networks:
      - mdp2mailservice-network
