"""Initial

Revision ID: 402ecfbf9485
Revises:
Create Date: 2024-11-19 17:45:58.139955

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "402ecfbf9485"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mails",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False, comment="uuid"),
        sa.Column("to_recipients", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("cc_recipients", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "QUEUED",
                "SENT",
                "FAILED",
                "DELIVERED",
                "REJECTED",
                name="deliverystatus",
                create_type=False,
                schema="mdp2mailservice",
            ),
            server_default=sa.text("'DRAFT'"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="created_at"),
        sa.Column("updated_at", sa.DateTime(), nullable=True, comment="updated_at"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mails")),
        schema="mdp2mailservice",
    )
    op.create_index(
        op.f("ix_mdp2mailservice_mails_status"), "mails", ["status"], unique=False, schema="mdp2mailservice"
    )
    op.create_index(
        op.f("ix_mdp2mailservice_mails_subject"), "mails", ["subject"], unique=False, schema="mdp2mailservice"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mdp2mailservice_mails_subject"), table_name="mails", schema="mdp2mailservice")
    op.drop_index(op.f("ix_mdp2mailservice_mails_status"), table_name="mails", schema="mdp2mailservice")
    op.drop_table("mails", schema="mdp2mailservice")

    op.execute("drop type if exists mdp2mailservice.deliverystatus")
    # ### end Alembic commands ###
